CREATE TABLE BOARD (
	BOARD_ID INT PRIMARY KEY AUTO_INCREMENT,
	BOARD_TITLE VARCHAR(20) NOT NULL,
	BOARD_CONTENT TEXT,
	BOARD_DATE DATETIME NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	HIT INT DEFAULT 0,
	FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)