CREATE TABLE MEETING (
	MEET_ID INT PRIMARY KEY AUTO_INCREMENT,
	MEET_NAME VARCHAR(20) NOT NULL,
	MEET_DATE DATE NOT NULL,
	MEET_START TIME NOT NULL,
	MEET_END TIME NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)