CREATE TABLE RIPPLE (
	RIPPLE_ID INT PRIMARY KEY AUTO_INCREMENT,
	BOARD_ID INT NOT NULL,
	RIPPLE_CONTENT TEXT,
	USER_ID VARCHAR(20) NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID)
)